"""Add priority, due_date, tags, and recurrence_rule to tasks

Revision ID: 57b259b29a5e
Revises: 
Create Date: 2026-01-02 20:15:01.316353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b259b29a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=False, server_default='MEDIUM'))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_rule', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_rule')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
